No1 = int(input("Enter First Number : "))
No2 = int(input("Enter Second Number : "))
print("Addition : ",(No1+No2))
print("Substraction : ",(No1-No2))
print("Multiplication : ",(No1*No2))
print("Division : ",(No1/No2))
